
package io.avreen.iso8583.mapper.impl;

import io.avreen.iso8583.mapper.api.ISOComponentMapper;
import io.avreen.iso8583.mapper.impl.base.ISOMsgBaseMapper;

/**
 * The class Iso 93 a mapper.
 */
public class ISO93AMapper extends ISOMsgBaseMapper {
    /**
     * The Fld.
     */
    protected ISOComponentMapper fieldsMapper[] = {
            /*000*/ IFA.NUM(4, "Message Type Indicator"),
            /*001*/ IFA.BITMAP(16, "Bitmap"),
            /*002*/ IFA.VARNUM(19, "Primary Account number"),
            /*003*/ IFA.NUM(6, "Processing Code"),
            /*004*/ IFA.NUM(12, "Amount, Transaction"),
            /*005*/ IFA.NUM(12, "Amount, Reconciliation"),
            /*006*/ IFA.NUM(12, "Amount, Cardholder billing"),
            /*007*/ IFA.NUM(10, "Date and time, transmission"),
            /*008*/ IFA.NUM(8, "Amount, Cardholder billing fee"),
            /*009*/ IFA.NUM(8, "Conversion rate, Reconciliation"),
            /*010*/ IFA.NUM(8, "Conversion rate, Cardholder billing"),
            /*011*/ IFA.NUM(6, "Systems trace audit number"),
            /*012*/ IFA.NUM(12, "Date and time, Local transaction"),
            /*013*/ IFA.NUM(4, "Date, Effective"),
            /*014*/ IFA.NUM(4, "Date, Expiration"),
            /*015*/ IFA.NUM(6, "Date, Settlement"),
            /*016*/ IFA.NUM(4, "Date, Conversion"),
            /*017*/ IFA.NUM(4, "Date, Capture"),
            /*018*/ IFA.NUM(4, "Merchant type"),
            /*019*/ IFA.NUM(3, "Country code, Acquiring institution"),
            /*020*/ IFA.NUM(3, "Country code, Primary account number"),
            /*021*/ IFA.NUM(3, "Country code, Forwarding institution"),
            /*022*/ IFA.CHAR(12, "Point of service data code"),
            /*023*/ IFA.NUM(3, "Card sequence number"),
            /*024*/ IFA.NUM(3, "Function code"),
            /*025*/ IFA.NUM(4, "Message reason code"),
            /*026*/ IFA.NUM(4, "Card acceptor business code"),
            /*027*/ IFA.NUM(1, "Approval code length"),
            /*028*/ IFA.NUM(6, "Date, Reconciliation"),
            /*029*/ IFA.NUM(3, "Reconciliation indicator"),
            /*030*/ IFA.NUM(24, "Amounts, original"),
            /*031*/ IFA.VARCHAR(99, "Acquirer reference data"),
            /*032*/ IFA.VARNUM(11, "Acquirer institution identification code"),
            /*033*/ IFA.VARNUM(11, "Forwarding institution identification code"),
            /*034*/ IFA.VARCHAR(28, "Primary account number, extended"),
            /*035*/ IFA.VARCHAR(37, "Track 2 data"),
            /*036*/ IFA.VARCHAR(104, "Track 3 data"),
            /*037*/ IFA.CHAR(12, "Retrieval reference number"),
            /*038*/ IFA.CHAR(6, "Approval code"),
            /*039*/ IFA.NUM(3, "Action code"),
            /*040*/ IFA.NUM(3, "Service code"),
            /*041*/ IFA.CHAR(8, "Card acceptor terminal identification"),
            /*042*/ IFA.CHAR(15, "Card acceptor identification code"),
            /*043*/ IFA.VARCHAR(99, "Card acceptor name/location"),
            /*044*/ IFA.VARCHAR(99, "Additional response data"),
            /*045*/ IFA.VARCHAR(76, "Track 1 data"),
            /*046*/ IFA.VARCHAR(204, "Amounts, Fees"),
            /*047*/ IFA.VARCHAR(999, "Additional data - national"),
            /*048*/ IFA.VARCHAR(999, "Additional data - private"),
            /*049*/ IFA.CHAR(3, "Currency code, Transaction"),
            /*050*/ IFA.CHAR(3, "Currency code, Reconciliation"),
            /*051*/ IFA.CHAR(3, "Currency code, Cardholder billing"),
            /*052*/ IFA.BIN(8, "Personal identification number (PIN) data"),
            /*053*/ IFA.VARBIN(48, "Security related control information"),
            /*054*/ IFA.VARCHAR(120, "Amounts, additional"),
            /*055*/ IFA.VARBIN(255, "IC card system related data"),
            /*056*/ IFA.VARNUM(35, "Original data elements"),
            /*057*/ IFA.NUM(3, "Authorization life cycle code"),
            /*058*/ IFA.VARNUM(11, "Authorizing agent institution Id Code"),
            /*059*/ IFA.VARCHAR(999, "Transport data"),
            /*060*/ IFA.VARCHAR(999, "Reserved for national use"),
            /*061*/ IFA.VARCHAR(999, "Reserved for national use"),
            /*062*/ IFA.VARCHAR(999, "Reserved for private use"),
            /*063*/ IFA.VARCHAR(999, "Reserved for private use"),
            /*064*/ IFA.BIN(8, "Message authentication code field"),
            /*065*/ IFA.BIN(8, "Reserved for ISO use"),
            /*066*/ IFA.VARCHAR(204, "Amounts, original fees"),
            /*067*/ IFA.NUM(2, "Extended payment data"),
            /*068*/ IFA.NUM(3, "Country code, receiving institution"),
            /*069*/ IFA.NUM(3, "Country code, settlement institution"),
            /*070*/ IFA.NUM(3, "Country code, authorizing agent Inst."),
            /*071*/ IFA.NUM(8, "Message number"),
            /*072*/ IFA.VARCHAR(999, "Data record"),
            /*073*/ IFA.NUM(6, "Date, action"),
            /*074*/ IFA.NUM(10, "Credits, number"),
            /*075*/ IFA.NUM(10, "Credits, reversal number"),
            /*076*/ IFA.NUM(10, "Debits, number"),
            /*077*/ IFA.NUM(10, "Debits, reversal number"),
            /*078*/ IFA.NUM(10, "Transfer, number"),
            /*079*/ IFA.NUM(10, "Transfer, reversal number"),
            /*080*/ IFA.NUM(10, "Inquiries, number"),
            /*081*/ IFA.NUM(10, "Authorizations, number"),
            /*082*/ IFA.NUM(10, "Inquiries, reversal number"),
            /*083*/ IFA.NUM(10, "Payments, number"),
            /*084*/ IFA.NUM(10, "Payments, reversal number"),
            /*085*/ IFA.NUM(10, "Fee collections, number"),
            /*086*/ IFA.NUM(16, "Credits, amount"),
            /*087*/ IFA.NUM(16, "Credits, reversal amount"),
            /*088*/ IFA.NUM(16, "Debits, amount"),
            /*089*/ IFA.NUM(16, "Debits, reversal amount"),
            /*090*/ IFA.NUM(10, "Authorizations, reversal number"),
            /*091*/ IFA.NUM(3, "Country code, transaction Dest. Inst."),
            /*092*/ IFA.NUM(3, "Country code, transaction Orig. Inst."),
            /*093*/ IFA.VARNUM(11, "Transaction Dest. Inst. Id code"),
            /*094*/ IFA.VARNUM(11, "Transaction Orig. Inst. Id code"),
            /*095*/ IFA.VARCHAR(99, "Card issuer reference data"),
            /*096*/ IFA.VARBIN(999, "Key management data"),
            /*097*/ IFA.NUM(1 + 16, "Amount, Net reconciliation"),
            /*098*/ IFA.CHAR(25, "Payee"),
            /*099*/ IFA.VARCHAR(11, "Settlement institution Id code"),
            /*100*/ IFA.VARNUM(11, "Receiving institution Id code"),
            /*101*/ IFA.VARCHAR(17, "File name"),
            /*102*/ IFA.VARCHAR(28, "Account identification 1"),
            /*103*/ IFA.VARCHAR(28, "Account identification 2"),
            /*104*/ IFA.VARCHAR(100, "Transaction description"),
            /*105*/ IFA.NUM(16, "Credits, Chargeback amount"),
            /*106*/ IFA.NUM(16, "Debits, Chargeback amount"),
            /*107*/ IFA.NUM(10, "Credits, Chargeback number"),
            /*108*/ IFA.NUM(10, "Debits, Chargeback number"),
            /*109*/ IFA.VARCHAR(84, "Credits, Fee amounts"),
            /*110*/ IFA.VARCHAR(84, "Debits, Fee amounts"),
            /*111*/ IFA.VARCHAR(999, "Reserved for ISO use"),
            /*112*/ IFA.VARCHAR(999, "Reserved for ISO use"),
            /*113*/ IFA.VARCHAR(999, "Reserved for ISO use"),
            /*114*/ IFA.VARCHAR(999, "Reserved for ISO use"),
            /*115*/ IFA.VARCHAR(999, "Reserved for ISO use"),
            /*116*/ IFA.VARCHAR(999, "Reserved for national use"),
            /*117*/ IFA.VARCHAR(999, "Reserved for national use"),
            /*118*/ IFA.VARCHAR(999, "Reserved for national use"),
            /*119*/ IFA.VARCHAR(999, "Reserved for national use"),
            /*120*/ IFA.VARCHAR(999, "Reserved for national use"),
            /*121*/ IFA.VARCHAR(999, "Reserved for national use"),
            /*122*/ IFA.VARCHAR(999, "Reserved for national use"),
            /*123*/ IFA.VARCHAR(999, "Reserved for private use"),
            /*124*/ IFA.VARCHAR(999, "Reserved for private use"),
            /*125*/ IFA.VARCHAR(999, "Reserved for private use"),
            /*126*/ IFA.VARCHAR(999, "Reserved for private use"),
            /*127*/ IFA.VARCHAR(999, "Reserved for private use"),
            /*128*/ IFA.BIN(8, "Message authentication code field")
    };

    /**
     * Instantiates a new Iso 93 a mapper.
     */
    public ISO93AMapper() {
        super();
        setFieldsMapper(fieldsMapper);
    }
}
