
package io.avreen.iso8583.mapper.impl;

import io.avreen.iso8583.mapper.api.ISOComponentMapper;
import io.avreen.iso8583.mapper.impl.base.ISOMsgBaseMapper;

/**
 * The class Iso 93 b mapper.
 */
public class ISO93BMapper extends ISOMsgBaseMapper {
    private static final boolean left_pad = false;
    /**
     * The Fld.
     */
    protected ISOComponentMapper fld[] = {
            /*000*/ IFB.NUM(4, "Message Type Indicator", left_pad),
            /*001*/ IFB.BITMAP(16, "Bitmap"),
            /*002*/ IFB.VARNUM(19, "Primary Account number", left_pad),
            /*003*/ IFB.NUM(6, "Processing Code", left_pad),
            /*004*/ IFB.NUM(12, "Amount, Transaction", left_pad),
            /*005*/ IFB.NUM(12, "Amount, Reconciliation", left_pad),
            /*006*/ IFB.NUM(12, "Amount, Cardholder billing", left_pad),
            /*007*/ IFB.NUM(10, "Date and time, transmission", left_pad),
            /*008*/ IFB.NUM(8, "Amount, Cardholder billing fee", left_pad),
            /*009*/ IFB.NUM(8, "Conversion rate, Reconciliation", left_pad),
            /*010*/ IFB.NUM(8, "Conversion rate, Cardholder billing", left_pad),
            /*011*/ IFB.NUM(6, "Systems trace audit number", left_pad),
            /*012*/ IFB.NUM(12, "Date and time, Local transaction", left_pad),
            /*013*/ IFB.NUM(4, "Date, Effective", left_pad),
            /*014*/ IFB.NUM(4, "Date, Expiration", left_pad),
            /*015*/ IFB.NUM(6, "Date, Settlement", left_pad),
            /*016*/ IFB.NUM(4, "Date, Conversion", left_pad),
            /*017*/ IFB.NUM(4, "Date, Capture", left_pad),
            /*018*/ IFB.NUM(4, "Merchant type", left_pad),
            /*019*/ IFB.NUM(3, "Country code, Acquiring institution", left_pad),
            /*020*/ IFB.NUM(3, "Country code, Primary account number", left_pad),
            /*021*/ IFB.NUM(3, "Country code, Forwarding institution", left_pad),
            /*022*/ IFA.CHAR(12, "Point of service data code"),
            /*023*/ IFB.NUM(3, "Card sequence number", left_pad),
            /*024*/ IFB.NUM(3, "Function code", left_pad),
            /*025*/ IFB.NUM(4, "Message reason code", left_pad),
            /*026*/ IFB.NUM(4, "Card acceptor business code", left_pad),
            /*027*/ IFB.NUM(1, "Approval code length", left_pad),
            /*028*/ IFB.NUM(6, "Date, Reconciliation", left_pad),
            /*029*/ IFB.NUM(3, "Reconciliation indicator", left_pad),
            /*030*/ IFB.NUM(24, "Amounts, original", left_pad),
            /*031*/ IFB.VARCHAR(99, "Acquirer reference data"),
            /*032*/ IFB.VARNUM(11, "Acquirer institution ident code", left_pad),
            /*033*/ IFB.VARNUM(11, "Forwarding institution ident code", left_pad),
            /*034*/ IFB.VARCHAR(28, "Primary account number, extended"),
            /*035*/ IFB.VARCHAR(37, "Track 2 data"),
            /*036*/ IFB.VARCHAR(104, "Track 3 data"),
            /*037*/ IFA.CHAR(12, "Retrieval reference number"),
            /*038*/ IFA.CHAR(6, "Approval code"),
            /*039*/ IFB.NUM(3, "Action code", left_pad),
            /*040*/ IFB.NUM(3, "Service code", left_pad),
            /*041*/ IFA.CHAR(8, "Card acceptor terminal identification"),
            /*042*/ IFA.CHAR(15, "Card acceptor identification code"),
            /*043*/ IFB.VARCHAR(99, "Card acceptor name/location"),
            /*044*/ IFB.VARCHAR(99, "Additional response data"),
            /*045*/ IFB.VARCHAR(76, "Track 1 data"),
            /*046*/ IFB.VARCHAR(204, "Amounts, Fees"),
            /*047*/ IFB.VARCHAR(999, "Additional data - national"),
            /*048*/ IFB.VARCHAR(999, "Additional data - private"),
            /*049*/ IFA.CHAR(3, "Currency code, Transaction"),
            /*050*/ IFA.CHAR(3, "Currency code, Reconciliation"),
            /*051*/ IFA.CHAR(3, "Currency code, Cardholder billing"),
            /*052*/ IFB.BIN(8, "Personal identification number (PIN) data"),
            /*053*/ IFB.VARBIN(48, "Security related control information"),
            /*054*/ IFB.VARCHAR(120, "Amounts, additional"),
            /*055*/ IFB.VARBIN(255, "IC card system related data"),
            /*056*/ IFB.VARNUM(35, "Original data elements", left_pad),
            /*057*/ IFB.NUM(3, "Authorization life cycle code", left_pad),
            /*058*/ IFB.VARNUM(11, "Authorizing agent institution Id Code", left_pad),
            /*059*/ IFB.VARCHAR(999, "Transport data"),
            /*060*/ IFB.VARCHAR(999, "Reserved for national use"),
            /*061*/ IFB.VARCHAR(999, "Reserved for national use"),
            /*062*/ IFB.VARCHAR(999, "Reserved for private use"),
            /*063*/ IFB.VARCHAR(999, "Reserved for private use"),
            /*064*/ IFB.BIN(8, "Message authentication code field"),
            /*065*/ IFB.BIN(8, "Reserved for ISO use"),
            /*066*/ IFB.VARCHAR(204, "Amounts, original fees"),
            /*067*/ IFB.NUM(2, "Extended payment data", left_pad),
            /*068*/ IFB.NUM(3, "Country code, receiving institution", left_pad),
            /*069*/ IFB.NUM(3, "Country code, settlement institution", left_pad),
            /*070*/ IFB.NUM(3, "Country code, authorizing agent Inst.", left_pad),
            /*071*/ IFB.NUM(8, "Message number", left_pad),
            /*072*/ IFB.VARCHAR(999, "Data record"),
            /*073*/ IFB.NUM(6, "Date, action", left_pad),
            /*074*/ IFB.NUM(10, "Credits, number", left_pad),
            /*075*/ IFB.NUM(10, "Credits, reversal number", left_pad),
            /*076*/ IFB.NUM(10, "Debits, number", left_pad),
            /*077*/ IFB.NUM(10, "Debits, reversal number", left_pad),
            /*078*/ IFB.NUM(10, "Transfer, number", left_pad),
            /*079*/ IFB.NUM(10, "Transfer, reversal number", left_pad),
            /*080*/ IFB.NUM(10, "Inquiries, number", left_pad),
            /*081*/ IFB.NUM(10, "Authorizations, number", left_pad),
            /*082*/ IFB.NUM(10, "Inquiries, reversal number", left_pad),
            /*083*/ IFB.NUM(10, "Payments, number", left_pad),
            /*084*/ IFB.NUM(10, "Payments, reversal number", left_pad),
            /*085*/ IFB.NUM(10, "Fee collections, number", left_pad),
            /*086*/ IFB.NUM(16, "Credits, amount", left_pad),
            /*087*/ IFB.NUM(16, "Credits, reversal amount", left_pad),
            /*088*/ IFB.NUM(16, "Debits, amount", left_pad),
            /*089*/ IFB.NUM(16, "Debits, reversal amount", left_pad),
            /*090*/ IFB.NUM(10, "Authorizations, reversal number", left_pad),
            /*091*/ IFB.NUM(3, "Country code, transaction Dest. Inst.", left_pad),
            /*092*/ IFB.NUM(3, "Country code, transaction Orig. Inst.", left_pad),
            /*093*/ IFB.VARNUM(11, "Transaction Dest. Inst. Id code", left_pad),
            /*094*/ IFB.VARNUM(11, "Transaction Orig. Inst. Id code", left_pad),
            /*095*/ IFB.VARCHAR(99, "Card issuer reference data"),
            /*096*/ IFB.VARBIN(999, "Key management data"),
            /*097*/ IFB.NUM(1 + 16, "Amount, Net reconciliation", left_pad),
            /*098*/ IFA.CHAR(25, "Payee"),
            /*099*/ IFB.VARCHAR(11, "Settlement institution Id code"),
            /*100*/ IFB.VARNUM(11, "Receiving institution Id code", left_pad),
            /*101*/ IFB.VARCHAR(17, "File name"),
            /*102*/ IFB.VARCHAR(28, "Account identification 1"),
            /*103*/ IFB.VARCHAR(28, "Account identification 2"),
            /*104*/ IFB.VARCHAR(100, "Transaction description"),
            /*105*/ IFB.NUM(16, "Credits, Chargeback amount", left_pad),
            /*106*/ IFB.NUM(16, "Debits, Chargeback amount", left_pad),
            /*107*/ IFB.NUM(10, "Credits, Chargeback number", left_pad),
            /*108*/ IFB.NUM(10, "Debits, Chargeback number", left_pad),
            /*109*/ IFB.VARCHAR(84, "Credits, Fee amounts"),
            /*110*/ IFB.VARCHAR(84, "Debits, Fee amounts"),
            /*111*/ IFB.VARCHAR(999, "Reserved for ISO use"),
            /*112*/ IFB.VARCHAR(999, "Reserved for ISO use"),
            /*113*/ IFB.VARCHAR(999, "Reserved for ISO use"),
            /*114*/ IFB.VARCHAR(999, "Reserved for ISO use"),
            /*115*/ IFB.VARCHAR(999, "Reserved for ISO use"),
            /*116*/ IFB.VARCHAR(999, "Reserved for national use"),
            /*117*/ IFB.VARCHAR(999, "Reserved for national use"),
            /*118*/ IFB.VARCHAR(999, "Reserved for national use"),
            /*119*/ IFB.VARCHAR(999, "Reserved for national use"),
            /*120*/ IFB.VARCHAR(999, "Reserved for national use"),
            /*121*/ IFB.VARCHAR(999, "Reserved for national use"),
            /*122*/ IFB.VARCHAR(999, "Reserved for national use"),
            /*123*/ IFB.VARCHAR(999, "Reserved for private use"),
            /*124*/ IFB.VARCHAR(999, "Reserved for private use"),
            /*125*/ IFB.VARCHAR(999, "Reserved for private use"),
            /*126*/ IFB.VARCHAR(999, "Reserved for private use"),
            /*127*/ IFB.VARCHAR(999, "Reserved for private use"),
            /*128*/ IFB.BIN(8, "Message authentication code field")
    };

    /**
     * Instantiates a new Iso 93 b mapper.
     */
    public ISO93BMapper() {
        super();
        setFieldsMapper(fld);
    }
}
